name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - main
      - master
      - feature/cicd

jobs:
  publish_docs:
    uses: nolte/gh-plumbing/.github/workflows/reuseable-mkdocs.yaml@develop
    with:
      requirements: "./requirementsDocs.txt"
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
