name: Publish docs via GitHub Pages
on:
  release:
    types: [published]

jobs:
  publish_docs:
    uses: nolte/gh-plumbing/.github/workflows/reuseable-mkdocs.yaml@v1.0.22
    with:
      requirements: "./requirementsDocs.txt"
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
