name: galaxy-role

on:
  release:
    types: [published]

jobs:
  push_role:
    uses: nolte/gh-plumbing/.github/workflows/reuseable-ansible-galaxy-push.yaml@v1.0.22
    secrets:
      galaxy_api_key: ${{ secrets.galaxy_api_key }}
