name: molecule e2e

on:
  push:
    paths-ignore:
    - 'docs/**'
    - 'requirementsDocs.txt'
    - '.devcontainer'


jobs:
  molecule:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        python-version: [3.8.5]    
        jdk-version: 
          - 11
          - 16
          - 17
    steps:
     - uses: actions/checkout@v2.4.0

     - uses: actions/setup-python@v2
       with:
         python-version: "${{ matrix.python-version }}"
         architecture: 'x64'

     - uses: gofrolist/molecule-action@v2
       env:
          MOLECULE_JDK_USED_VERSION: "${{ matrix.jdk-version }}"

     #- name: Install dependencies
     #  run: |
     #    python -m pip install --upgrade pip
     #    pip install -r ./requirementsDev.txt
#
     #- name: Test with molecule
     #  run: molecule test
     #  env:
     #   MOLECULE_JDK_USED_VERSION: "${{ matrix.jdk-version }}"